# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-01 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBN_Garage', '0002_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(default='pending', max_length=16),
        ),
    ]
